/*
Q1. What is the total revenue generated by male vs. female customers?
Q2. Which customers used a discount but still spent more than the average purchase amount?
Q3. Which are the top 5 products with the highest average review rating?
Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
Q8. What are the top 3 most purchased products within each category?
Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Q10. What is the revenue contribution of each age group? */
USE customer_behavior;

-- Q1. Total revenue (Male vs Female)
SELECT Gender, SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer
GROUP BY Gender;


-- Q2. Discount use kiya but avg se zyada spend
SELECT *
FROM customer
WHERE `Discount Applied` = 'Yes'
AND `Purchase Amount (USD)` > (
    SELECT AVG(`Purchase Amount (USD)`) FROM customer
);


-- Q3. Top 5 products (highest avg rating)
SELECT `Item Purchased`, AVG(`Review Rating`) AS avg_rating
FROM customer
GROUP BY `Item Purchased`
ORDER BY avg_rating DESC
LIMIT 5;


-- Q4. Standard vs Express (avg purchase)
SELECT `Shipping Type`, AVG(`Purchase Amount (USD)`) AS avg_purchase
FROM customer
GROUP BY `Shipping Type`;


-- Q5. Subscribers vs Non-subscribers
SELECT `Subscription Status`,
       AVG(`Purchase Amount (USD)`) AS avg_spend,
       SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer
GROUP BY `Subscription Status`;


-- Q6. Top 5 products (highest discount %)
SELECT `Item Purchased`,
       COUNT(CASE WHEN `Discount Applied` = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_percentage
FROM customer
GROUP BY `Item Purchased`
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q7. Customer Segmentation
SELECT 
    CASE 
        WHEN `Previous Purchases` = 0 THEN 'New'
        WHEN `Previous Purchases` BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS total_customers
FROM customer
GROUP BY customer_segment;


-- Q8. Top 3 products in each category
SELECT `Category`, `Item Purchased`, total_purchases
FROM (
    SELECT `Category`, `Item Purchased`, COUNT(*) AS total_purchases,
           RANK() OVER (PARTITION BY `Category` ORDER BY COUNT(*) DESC) AS rnk
    FROM customer
    GROUP BY `Category`, `Item Purchased`
) sub
WHERE rnk <= 3;


-- Q9. Repeat buyers vs Subscription
SELECT 
    CASE 
        WHEN `Previous Purchases` > 5 THEN 'Repeat Buyer'
        ELSE 'Normal Buyer'
    END AS buyer_type,
    `Subscription Status`,
    COUNT(*) AS total_customers
FROM customer
GROUP BY buyer_type, `Subscription Status`;


-- Q10. Revenue by Age Group
SELECT 
    CASE 
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END AS age_group,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer
GROUP BY age_group;